## Learning goals
- Create 1D/2D NumPy arrays
- Indexing, slicing, and vectorized operations
- Use aggregations (`mean`, `std`, …) as **NumPy syntax** (stats meaning was Week 2)


In [1]:
# Purpose: load NumPy

import numpy as np

### Create arrays


In [9]:
# Purpose: create 1D and 2D arrays

a = np.array([1, 2, 3, 4, 5])  # 1D array from a list
print(a, a.dtype, a.shape)     # values, data type, and length of each axis


[1 2 3 4 5] int64 (5,)


The comma in (5,) is required Python: (5) is just the number 5; (5,) is a tuple of length 1. NumPy uses that to show “one axis, not two.”

In [3]:
zeros = np.zeros(5)           # 1D array of five 0s
ones = np.ones((2, 3))        # 2×3 array of 1s
seq = np.arange(0, 10, 2)     # 0, 2, 4, 6, 8 (start, stop, step)
print(zeros)                  # display zeros
print(ones)                   # display the 2×3 ones
print(seq)                    # display the even numbers

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]


### Indexing and slicing


In [10]:
# Purpose: indexing and slicing

print(a[0], a[-1])
print(a[1:4])
M = np.array([[10,20,30],[40,50,60]])
print(M[0,1])
print(M[:,1])  # second column


1 5
[2 3 4]
20
[20 50]


### Aggregations
These are the same summaries as Week 2. Here we observe **NumPy syntax**: one method on the whole array (`x.mean()`), not a Python loop. A **list** has no `.mean()` and cannot be compared to 4 in one step.


In [11]:
# Purpose: aggregations as NumPy syntax (mean, SD, min, max, count)

wait_list = [2.0, 4.0, 4.0, 4.0, 5.0, 5.0, 7.0, 9.0]
print(sum(wait_list) / len(wait_list))  # mean by hand — a list has no .mean()
# wait_list.mean()   # AttributeError — uncomment to see
# wait_list > 4      # TypeError — uncomment to see

x = np.array(wait_list)  # same values, now an array
print(x.mean(), x.std(ddof=1), x.min(), x.max())
print(x.sum(), (x > 4).sum())  # count how many values are greater than 4


5.0
5.0 2.138089935299395 2.0 9.0
40.0 4


### Vectorized operations


In [12]:
# Purpose: vectorized operations (no loop)

print(a * 2)
print(a + np.array([10,10,10,10,10]))


[ 2  4  6  8 10]
[11 12 13 14 15]


### Exercise
1. Create an array of 20 draws from `np.random.normal(loc=100, scale=15)`.
2. Report mean and SD.
3. What fraction of values are above 115?


In [13]:
# Your code here
draws = np.random.normal(loc=100,scale=15,size=20)
print(draws.mean)
print(draws.std)

<built-in method mean of numpy.ndarray object at 0x70dd55356130>
<built-in method std of numpy.ndarray object at 0x70dd55356130>
